/*
   This file was generated automatically by Alchitry Labs version 1.2.0.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module seven_seg_7 (
    input [4:0] char,
    output reg [6:0] segs
  );
  
  
  
  always @* begin
    
    case (char)
      5'h00: begin
        segs = 7'h3f;
      end
      5'h01: begin
        segs = 7'h06;
      end
      5'h02: begin
        segs = 7'h5b;
      end
      5'h03: begin
        segs = 7'h4f;
      end
      5'h04: begin
        segs = 7'h66;
      end
      5'h05: begin
        segs = 7'h6d;
      end
      5'h06: begin
        segs = 7'h7d;
      end
      5'h07: begin
        segs = 7'h07;
      end
      5'h08: begin
        segs = 7'h7f;
      end
      5'h09: begin
        segs = 7'h67;
      end
      5'h0a: begin
        segs = 7'h77;
      end
      5'h0b: begin
        segs = 7'h7c;
      end
      5'h0c: begin
        segs = 7'h39;
      end
      5'h0d: begin
        segs = 7'h5e;
      end
      5'h0e: begin
        segs = 7'h79;
      end
      5'h0f: begin
        segs = 7'h79;
      end
      5'h10: begin
        segs = 7'h71;
      end
      5'h11: begin
        segs = 7'h76;
      end
      5'h12: begin
        segs = 7'h38;
      end
      5'h13: begin
        segs = 7'h54;
      end
      5'h14: begin
        segs = 7'h73;
      end
      5'h15: begin
        segs = 7'h50;
      end
      5'h16: begin
        segs = 7'h6d;
      end
      5'h17: begin
        segs = 7'h3e;
      end
      default: begin
        segs = 7'h00;
      end
    endcase
  end
endmodule
